### ISSUE TITLE
Implementation is broken when script has errors

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge-ruby#1]
test.spec:

```
# Test

## Test1

* test
```

step_implementation.rb:

```
step "test" do
    puts this should fail # syntax error
end
````

This should have failed with a decent message. But it crashed with the following message.

```
/Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:64:in `write': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:64:in `serialize_field_value'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protoc* testfers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:51:in `serialize_field'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:38:in `block in encode'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:15:in `each'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:15:in `encode'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:248:in `serialize'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:255:in `serialize_to_string'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/field.rb:611:in `serialize'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:38:in `block in encode'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:15:in `each'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:15:in `encode'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:248:in `serialize'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:255:in `serialize_to_st" Press ? for help             |  1
ring'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/field.rb:611:in `serialize'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:38:in `block in encode'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:15:in `each'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/encoder.rb:15:in `encode'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:248:in `serialize'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:255:in `serialize_to_string'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/gauge-ruby-0.0.3/lib/gauge-runtime.rb:40:in `write_message'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/gauge-ruby-0.0.3/lib/gauge-runtime.rb:35:in `handle_message'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/gauge-ruby-0.0.3/lib/gauge-runtime.rb:18:in `dispatch_messages'
	from /Users/navaneethkn/.rvm/gems/ruby-2.1.3@fundhive/gems/gauge-ruby-0.0.3/lib/gauge-runtime.rb:57:in `<top (required)>'
	from /Users/navaneethkn/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/navaneethkn/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/navaneethkn/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from -e:1:in `<main>'
Failed to start Gauge Ruby runner. exit status 1e of closed network connection
Runner exited with error: exit status 1

The following failures occured:

/Users/navaneethkn/projects/spectra/rewrite/fundhive/functional-tests/specs/test.spec : Test
 Test1:
	 test
Connection closed [127.0.0.1:60498] cause: EOF

use of closed network connectionuse of closed network connectionuse of closed network connectionuse of closed network connection
```

**Comment by prateekbaheti** [comment]
On further inspection we found that this is a [ruby-protocol-buffers](https://github.com/codekitchen/ruby-protocol-buffers) gem issue on ruby 2.1.3.
