### ISSUE TITLE
Refactor with step text is changing the parameter name

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#29]
**Expected behavior**
The parameter name should not change until it is a new parameter

**Actual behavior**
The parameter name is being changed even with the refactored text retaining the old name.

**Steps to replicate**
1. Create a project

```
gauge --init ruby
```
1. With spec details

```
Specification Heading
=====================

This is an executable specification file. This file follows markdown syntax.
Every heading in this file denotes a scenario. Every bulleted point denotes a step.

To execute this specification, run

    gauge specs


* sdf"a"

Vowel counts in single word
---------------------------

tags: single word

* The word "gauge" has "3" vowels.

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* Almost all words have vowels

     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |
```
1. With implementation

```
require 'test/unit'
include Test::Unit::Assertions

@vowels = nil;

step 'sdf<vowels>' do |vowels|
   @vowels = vowels.scan(/./);
end

step 'The word <word> has <count> vowels.' do |word, expectedCount|
  assert_equal(expectedCount.to_i, count_vowels(word))
end

step 'Almost all words have vowels <table>' do |wordsTable|
  wordsTable.rows().each do |row|
    word = row[0];
    expectedCount = row[1].to_i
    actualCount = count_vowels(word)
    assert_equal(expectedCount, actualCount)
  end
end

def count_vowels(string)
  string.count(@vowels.to_s)
end
```
1. Refactor the step using the `step text` in the spec
   gauge --refactor "sdf\"a\"" "Vowels in English language are <vowels>."
2. This refactors the step and renames the parameter to `arg_vowels`

**Version**

```
Gauge version: 0.5.1.nightly-2016-07-10

Plugins
-------
html-report (2.1.1.nightly-2016-07-08)
java (0.4.2.nightly-2016-07-07)
ruby (0.2.1)
```

**Comment by kashishm** [comment]
Cannot reproduce this with the latest gauge-ruby.

**Comment by sguptatw** [comment]
Unable to test as I am getting the following exception with the project 
[ruby.zip](https://github.com/getgauge/gauge-ruby/files/723206/ruby.zip)

```
/Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/decoder.rb:86:in `decode': invalid message (ProtocolBuffers::DecodeError)
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:290:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:296:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/field.rb:615:in `deserialize'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/decoder.rb:60:in `decode'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:290:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:296:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/bundler/gems/gauge-ruby-00080b0f5151/lib/gauge_runtime.rb:36:in `dispatch_messages'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/bundler/gems/gauge-ruby-00080b0f5151/lib/gauge_runtime.rb:76:in `<module:Runtime>'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/bundler/gems/gauge-ruby-00080b0f5151/lib/gauge_runtime.rb:29:in `<module:Gauge>'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.3/bundler/gems/gauge-ruby-00080b0f5151/lib/gauge_runtime.rb:27:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example.spec:12 Step implementation not found => 'Vowels in English language are "aeiou".'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example.spec:13 Step implementation not found => 'Add "product" to basket1'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example.spec:14 Step implementation not found => '"hgfh"'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example.spec:21 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example.spec:30 Step implementation not found => 'Almost all words have vowels <table>'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example0.spec:10 Step implementation not found => 'sdf "a"'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example0.spec:11 Connection closed [[::1]:56972] cause: EOF => 'Vowels in English language are .'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example0.spec:12 Step implementation not found => 'Vowels in English language are "aeiou".'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example0.spec:13 Step implementation not found => 'Add "product" to basket1'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example0.spec:20 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example0.spec:29 Step implementation not found => 'Almost all words have vowels <table>'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example1.spec:12 Step implementation not found => 'Vowels in English language are "aeiou".'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example1.spec:13 Step implementation not found => 'Add "product" to basket1'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example1.spec:14 Step implementation not found => '"hgfh"'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example1.spec:21 Step implementation not found => 'The word "gauge" has "3" vowels.'
[ValidationError] /Users/sswaroop/work/gauge_git/ruby/specs/example1.spec:30 Step implementation not found => 'Almost all words have vowels <table>'
Ruby runner Failed. Reason: exit status 1
  Failed to initialize suite datastore. Error: write tcp [::1]:56968->[::1]:56972: use of closed network connection
Successfully generated html-report to => /Users/sswaroop/work/gauge_git/ruby/reports/html-report
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	6 skipped
```

**Comment by sriv** [comment]
@sguptatw - can you please verify again with the released version?
