### ISSUE TITLE
$ gauge specs /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gauge_runtime

### ISSUE THREAD

**Issue by baychae** [getgauge/gauge-ruby#37]
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

- Installed gauge using .pkg into macOS Sierra (osx 10.12.3) installing all language options.

- Successfully initiated project.

- Error on gauge specs:

$ gauge specs
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gauge_runtime (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
Ruby runner Failed. Reason: exit status 1
Failed to start gauge API: Runner with pid 44476 quit unexpectedly(exit status 1).

![screen shot 2017-04-05 at 11 42 12](https://cloud.githubusercontent.com/assets/2361802/24702213/bb4d4c62-19f5-11e7-9832-4b1eafa82993.png)

$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.2.0)
bundler (1.14.6)
CFPropertyList (2.2.8)
io-console (default: 0.4.2)
json (default: 1.7.7)
libxml-ruby (2.6.0)
minitest (default: 4.3.2)
nokogiri (1.5.6)
psych (default: 2.0.0)
rake (default: 0.9.6)
rdoc (default: 4.0.0)
rubygems-update (2.6.11)
sqlite3 (1.3.7)
test-unit (default: 2.0.0.0)

**Comment by baychae** [comment]
sudo gem install gauge-ruby resolves this issue.

Could this dependency either be included into .pkg or the Get Started docs please?
