### ISSUE TITLE
Unable to start Gauge API

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#39]
**Expected behavior**
Gauge specs must be executed when the command `gauge specs` is run in the command line

**Actual behavior**
In the released Gauge-ruby version Getting the following exception
```
/Users/sswaroop/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gauge_runtime (LoadError)
	from /Users/sswaroop/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
Ruby runner Failed. Reason: exit status 1
Failed to start gauge API: Runner with pid 44302 quit unexpectedly(exit status 1).
```
**Version**
```
Gauge version: 0.8.4.nightly-2017-05-10

Plugins
-------
html-report (4.0.0.nightly-2017-05-04)
java (0.6.3.nightly-2017-04-21)
ruby (0.4.0)
xml-report (0.2.0)
```

**Comment by kashishm** [comment]
@sguptatw Please run `bundle exec gauge specs`.

**Comment by sguptatw** [comment]
Getting the following error now
```
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 16 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/sswaroop/.rvm/gems/ruby-2.3.1:/Users/sswaroop/.rvm/gems/ruby-2.3.1@global', execute `gem env` for more information
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/bundle:22:in `<main>'
```

**Comment by kashishm** [comment]
@sguptatw Update `bundler`.
