### ISSUE TITLE
Getting Protobuff exception while trying to execute Gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#40]
**Expected behavior**
I should be able to execute the Gauge specs

**Actual behavior**
Getting the following exception
```
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.3-compliant syntax, but you are running 2.3.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/decoder.rb:86:in `decode': invalid message (ProtocolBuffers::DecodeError)
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:290:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:296:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/field.rb:615:in `deserialize'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/decoder.rb:60:in `decode'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:290:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/ruby-protocol-buffers-1.5.1/lib/protocol_buffers/runtime/message.rb:296:in `parse'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:36:in `dispatch_messages'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:76:in `<module:Runtime>'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:29:in `<module:Gauge>'
	from /Users/sswaroop/.rvm/gems/ruby-2.3.1/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:27:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/user.spec:3 Connection closed [[::1]:53861] cause: EOF => 'On signup page'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/user.spec:4 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Fill in and send registration form'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/user.spec:18 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'On the customer page'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/user.spec:19 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Just registered customer is listed'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/customer.md:7 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'On the customer page'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/customer.md:15 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Search for customer "ScroogeMcduck"'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/customer.md:16 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'The customer "ScroogeMcduck" is listed'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/customer.md:23 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Search for customers <table:resources/user.csv>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:8 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Create a product <table>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:3 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'On product page'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:4 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Search for product <name>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:5 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Open description for product <name>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:22 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Verify product "author" as "John P. Baugh"'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:29 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Find and store productId for "The Way to Go"'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:30 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Open product edit page for stored productId'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:31 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Update product specifier to new value <table:resources/product_data.csv>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:32 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Check product specifier has new value <table:resources/product_data.csv>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/concepts/find_and_open_product.cpt:3 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'On product page'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/concepts/find_and_open_product.cpt:4 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Search for product <name>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/concepts/find_and_open_product.cpt:5 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Open description for product <name>'
[ValidationError] /Users/sswaroop/blogResearch/gauge-example-ruby/specs/products.md:6 write tcp [::1]:53857->[::1]:53861: use of closed network connection => 'Delete this product'
Ruby runner Failed. Reason: exit status 1
  Failed to initialize suite datastore. Error: write tcp [::1]:53857->[::1]:53861: use of closed network connection
Successfully generated html-report to => /Users/sswaroop/blogResearch/gauge-example-ruby/reports/html-report
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 8ms
```

**Steps to replicate**
* Clone gauge-example-ruby
* Execute gauge from command line. Getting the following exception

**Version**
```
Gauge version: 0.8.4.nightly-2017-05-10

Plugins
-------
html-report (4.0.0.nightly-2017-05-04)
java (0.6.3.nightly-2017-04-21)
ruby (0.4.0)
xml-report (0.2.0)
```

**Comment by sguptatw** [comment]
Updated Gauge ruby and still getting the same exception
```
Gauge version: 0.8.4.nightly-2017-05-10

Plugins
-------
html-report (4.0.0.nightly-2017-05-04)
java (0.6.3.nightly-2017-04-21)
ruby (0.4.1.nightly-2017-05-08)
xml-report (0.2.0)
```

**Comment by kashishm** [comment]
@sguptatw update `gauge-ruby` gem to `0.4` in `Gemfile` and then run 
```
bundle install
bundle exec gauge specs
```

**Comment by sguptatw** [comment]
@kashishm : Solves the issue thanks.
