### ISSUE TITLE
On test failure print step implementation snippet 

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-ruby#44]
To easily debug test failures.
Print a snippet of the Step implementation with the line that failed and decrease verbosity of the stack trace.

e.g.
```
# Specification Heading
  ## Vowel counts in single word	 ✘
        Failed Step: The word "gauge" has "3" vowels.
        Specification: specs/example.spec:18
        Error Message: <3> expected but was
        <4>.
        Stacktrace:
        > 11 | assert_equal(expected_count.to_i, 4)
        /Users/apoorvag/tmp/step_implementations/step_implementation.rb:11:in `block in <top (required)>'

  ## Vowel counts in multiple word	 ✘
        Failed Step: Almost all words have vowels
        Specification: specs/example.spec:28
        Error Message: <3> expected but was
        <0>.
        Stacktrace:
        > 20 | assert_equal(expected_count, actual_count)
        /Users/apoorvag/tmp/step_implementations/step_implementation.rb:20:in `block (2 levels) in <top (required)>'
        /Users/apoorvag/tmp/step_implementations/step_implementation.rb:16:in `each'
        /Users/apoorvag/tmp/step_implementations/step_implementation.rb:16:in `block in <top (required)>'


  Error Message: no block given (yield)
  Stacktrace:
  > 29 | assert_fail_assertion()
  /Users/apoorvag/tmp/step_implementations/step_implementation.rb:29:in `block in <top (required)>'
```

**Comment by Apoorva-GA** [comment]
Should be available in gauge-ruby nightly >= 17/10/17.
