### ISSUE TITLE
An existing connection was forcibly closed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#65]
**Expected behavior**
Should process the current request without an exception

**Actual behavior**
Getting the following error
```
c:/work/getgauge/FT/gauge-lsp-tests/data/executionStatus_ruby/vendor/bundle/ruby/2.4.0/bundler/gems/gauge-ruby-cc52464a21cc/lib/gauge_runtime.rb:36:in `eof?': An existing connection was forcibly closed by the remote host. @ io_fillbuf - fd:3  (Errno::ECONNRESET)
	from c:/work/getgauge/FT/gauge-lsp-tests/data/executionStatus_ruby/vendor/bundle/ruby/2.4.0/bundler/gems/gauge-ruby-cc52464a21cc/lib/gauge_runtime.rb:36:in `dispatch_messages'
	from c:/work/getgauge/FT/gauge-lsp-tests/data/executionStatus_ruby/vendor/bundle/ruby/2.4.0/bundler/gems/gauge-ruby-cc52464a21cc/lib/gauge_runtime.rb:80:in `<module:Runtime>'
	from c:/work/getgauge/FT/gauge-lsp-tests/data/executionStatus_ruby/vendor/bundle/ruby/2.4.0/bundler/gems/gauge-ruby-cc52464a21cc/lib/gauge_runtime.rb:32:in `<module:Gauge>'
	from c:/work/getgauge/FT/gauge-lsp-tests/data/executionStatus_ruby/vendor/bundle/ruby/2.4.0/bundler/gems/gauge-ruby-cc52464a21cc/lib/gauge_runtime.rb:30:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
Ruby runner Failed. Reason: exit status 1
```
**Steps to replicate**
* Run LSP tests with env ruby-wd

**Version**
```
auge version: 0.9.8.nightly-2018-04-05
Commit Hash: 51a094a

Plugins
-------
html-report (4.0.4.nightly-2018-03-28)
js (2.2.0.nightly-2018-03-29)
ruby (0.4.3.nightly-2018-04-05)
```

**Comment by sguptatw** [comment]
Working as expected
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
ruby (0.5.2.nightly-2018-07-31)
```
