### ISSUE TITLE
Should be able to implement a parser in the default package

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#67]
**Expected behavior**
The package of the parser with custom implementation should not be restricted to ``

**Actual behavior**
Getting the following exception
```
/usr/local/bin/gauge run --machine-readable --hide-suggestion --simple-console .../basic4/specs/example.spec:13
java.lang.NullPointerException
	at com.thoughtworks.gauge.execution.parameters.parsers.base.ParameterParsingChain.isNotGaugeParser(ParameterParsingChain.java:32)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.thoughtworks.gauge.execution.parameters.parsers.base.ParameterParsingChain.<init>(ParameterParsingChain.java:25)
	at com.thoughtworks.gauge.execution.StepExecutionStage.<init>(StepExecutionStage.java:34)
	at com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:39)
	at com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:91)
	at com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
	at com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
	at com.thoughtworks.gauge.GaugeRuntime$2.run(GaugeRuntime.java:86)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
Failed: Vowels in English language are "aeiou".
Filename: .../basic4/specs/example.spec:10
Message: Connection closed [127.0.0.1:49447] cause: EOF


Failed: AfterStep hook for step: Vowels in English language are "aeiou".
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection


Failed: After Scenario
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection


Failed: After Specification
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection


Failed: After Suite
Message: write tcp 127.0.0.1:49443->127.0.0.1:49447: use of closed network connection
```
**Steps to replicate**
* Create a `gauge-java` project
* Create an implementation of the custom parser at the same level as `StepImplementation.java`
```
import com.thoughtworks.gauge.execution.parameters.parsers.base.CustomParameterParser;
import gauge.messages.Spec;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class LocalDateGaugeParser extends CustomParameterParser<LocalDate> {

    @Override
    public boolean canParse(Class<?> aClass, Spec.Parameter parameter) {
        return aClass.equals(LocalDate.class);
    }

    @Override
    protected LocalDate customParse(Class<?> aClass, Spec.Parameter parameter) {
        DateTimeFormatter f = DateTimeFormatter.ofPattern("MM dd, yyyy");
        return LocalDate.from(f.parse(parameter.getValue()));
    }
}
```
* Use this in a step `something with date "03 04,2018"`
* Give the implementation for the step
```
    @Step("something with date <date>")
    public void implementation1(java.time.LocalDate date) {
        System.out.println(date);
    }
```
* Run the spec
> The above exception occurs

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-11
Commit Hash: 4d314ef

Plugins
-------
html-report (4.0.4.nightly-2018-03-30)
java (0.6.7.nightly-2018-04-06)
js (2.2.0.nightly-2018-04-12)
python (0.3.0.nightly-2018-04-10)
report-seed (0.0.1)
ruby (0.5.0.nightly-2018-04-11)
screenshot (0.0.1)
```

**Comment by sguptatw** [comment]
This issue was moved to getgauge/gauge-java#142
