### ISSUE TITLE
Use of network connection closed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#70]
**Expected behavior**
Should be able to execute seamlessly

**Actual behavior**
Getting the following error
```
.../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/processors/execution_handler.rb:59:in `readlines': No such file or directory @ rb_sysopen - C (Errno::ENOENT)
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/processors/execution_handler.rb:59:in `get_code_snippet'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/processors/execution_handler.rb:44:in `handle_failure'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/processors/execute_step_request_processor.rb:32:in `rescue in process_execute_step_request'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/processors/execute_step_request_processor.rb:29:in `process_execute_step_request'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/message_processor.rb:56:in `call'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/message_processor.rb:56:in `process_message'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/gauge_runtime.rb:56:in `handle_message'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/gauge_runtime.rb:40:in `dispatch_messages'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/gauge_runtime.rb:80:in `<module:Runtime>'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/gauge_runtime.rb:32:in `<module:Gauge>'
        from .../ruby/one/vendor/bundle/ruby/2.4.0/gems/gauge-ruby-0.4.3/lib/gauge_runtime.rb:30:in `<top (required)>'
        from -e:1:in `require'
        from -e:1:in `<main>'

        Error Message: write tcp 127.0.0.1:60546->127.0.0.1:60550: use of closed network connection
        Stacktrace:


        Failed Step: Vowels in English language are "aeiou".
        Specification: specs\example.spec:11
        Error Message: Connection closed [127.0.0.1:60550] cause: EOF
        Stacktrace:


    Error Message: write tcp 127.0.0.1:60546->127.0.0.1:60550: use of closed network connection
    Stacktrace:

Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:60546->127.0.0.1:60550: use of closed network connection
  ## Vowel counts in multiple word
    Error Message: write tcp 127.0.0.1:60546->127.0.0.1:60550: use of closed network connection
    Stacktrace:



    Error Message: write tcp 127.0.0.1:60546->127.0.0.1:60550: use of closed network connection
    Stacktrace:

Ruby runner Failed. Reason: exit status 1
```

**Steps to replicate**
* Create a `gauge-ruby` project
* Change the implementation of `Vowels in English language are <vowels>` to 
```
step 'Vowels in English language are <vowels>.' do |vowels|
  assert_equal(1,2)
  @vowels = vowels.scan(/./)
end
```

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-19
Commit Hash: 58298e2

Plugins
----------
ruby (0.5.0.nightly-2018-04-16)
```

**Comment by sguptatw** [comment]
This happens only on Windows, currently we do not support ruby on Windows.
