### ISSUE TITLE
use of closed network connection while running specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#88]
_From @sguptatw on June 28, 2018 12:8_

**Expected behavior**
Should be able to run tests that fail seamlessly on Windows

**Actual behavior**
Getting use of network connection closed

**Steps to replicate**
* Create a gauge-ruby project
* Change the step `Vowels in English language are "aeiou"` to `Vowels in English language are "abcde"`
* Run the specs
> Getting the use of network connection closed message

**Version**
```
Gauge version: 1.0.1.nightly-2018-06-27
Commit Hash: 0e3c1fc

Plugins
-------
ruby (0.5.2.nightly-2018-06-19)
```

_Copied from original issue: getgauge/gauge#1106_

**Comment by sguptatw** [comment]
stacktrace
```
.../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/processors/execution_handler.rb:60:in `readlines': No such file or directory @ rb_sysopen - c (Errno::ENOENT)
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/processors/execution_handler.rb:60:in `get_code_snippet'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/processors/execution_handler.rb:44:in `handle_failure'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/processors/execute_step_request_processor.rb:32:in `rescue in process_execute_step_request'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/processors/execute_step_request_processor.rb:29:in `process_execute_step_request'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/message_processor.rb:58:in `call'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/message_processor.rb:58:in `process_message'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/gauge_runtime.rb:56:in `handle_message'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/gauge_runtime.rb:41:in `dispatch_messages'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/gauge_runtime.rb:85:in `<module:Runtime>'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/gauge_runtime.rb:33:in `<module:Gauge>'
	from .../vendor/bundle/ruby/2.5.0/bundler/gems/gauge-ruby-ea761da950e0/lib/gauge_runtime.rb:31:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'

```

**Comment by shubhamsc** [comment]
Fixed should be available in nightly >= 30-07-18
