### ISSUE TITLE
Failed to start Gauge API

### ISSUE THREAD

**Issue by ssaikumar** [getgauge/gauge-ruby#98]
$ bundle exec gauge run specs
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.4-compliant syntax, but you are running 2.4.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/Users/ssaikumar/.rvm/gems/ruby-2.4.2@global/gems/gauge-ruby-0.5.1/lib/messages_pb.rb:7:in `finalize_to_pool': Unable to add defs to DescriptorPool: Symtab already has a def named 'gauge.messages.KillProcessRequest' (RuntimeError)
	from /Users/ssaikumar/.rvm/gems/ruby-2.4.2@global/gems/gauge-ruby-0.5.1/lib/messages_pb.rb:7:in `build'
	from /Users/ssaikumar/.rvm/gems/ruby-2.4.2@global/gems/gauge-ruby-0.5.1/lib/messages_pb.rb:7:in `<top (required)>'
	from /Users/ssaikumar/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/gauge-ruby-0.5.1/lib/code_parser.rb:24:in `require'
	from /Users/ssaikumar/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/gauge-ruby-0.5.1/lib/code_parser.rb:24:in `<top (required)>'
	from /Users/ssaikumar/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/gauge-ruby-0.5.1/lib/static_loader.rb:19:in `require_relative'
	from /Users/ssaikumar/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/gauge-ruby-0.5.1/lib/static_loader.rb:19:in `<top (required)>'
	from /Users/ssaikumar/.rvm/gems/ruby-2.4.2@global/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:24:in `require_relative'
	from /Users/ssaikumar/.rvm/gems/ruby-2.4.2@global/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:24:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
Ruby runner Failed. Reason: exit status 1
Error ----------------------------------

Failed to start gauge API: Runner with pid 44481 quit unexpectedly(exit status 1).

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	darwin, 1.0.3
	html-report (4.0.6), ruby (0.5.1), screenshot (0.0.1)

**Comment by negiDharmendra** [comment]
@ssaikumar Her were you able to gather information @nehashri has asked for.
