### ISSUE TITLE
Adding `nil` to Gauge.write_message crashes the runner

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-ruby#99]
### Expected behavior
The runner should not be crashing 

### Actual behavior
The runner crashes when a null value is added to 

### Steps to reproduce
1. `gauge init ruby`
2. Update step implementation to have `Gauge.write_message(nil)` 
3. `bundle exec gauge run specs`

It throws following error and crashes the runner 
```
vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/processors/execution_hook_processors.rb:74:in `+': Invalid argument for string field. (TypeError)
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/processors/execution_hook_processors.rb:74:in `process_step_execution_end_request'
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/message_processor.rb:58:in `call'
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/message_processor.rb:58:in `process_message'
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:56:in `handle_message'
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:41:in `dispatch_messages'
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:85:in `<module:Runtime>'
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:33:in `<module:Gauge>'
	from vendor/bundle/ruby/2.3.0/gems/gauge-ruby-0.5.1/lib/gauge_runtime.rb:31:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```
### Gauge version
Gauge version: 1.0.4
Commit Hash: 5e997d2

Plugins
-------
csharp (0.10.6)
html-report (4.0.7)
java (0.7.0)
js (2.3.4)
python (0.3.5)
ruby (0.5.1)
screenshot (0.0.1)
xml-report (0.2.0)
```

**Comment by sguptatw** [comment]
[Blocker] - The latest nightly available is 0.5.2.nightly-2018-11-28
